/**
 * *********************************************************
 * DO NOT EDIT THIS FILE IN YOUR PROJECT UNLESS NECESSARY. *
 * IT CONTAINS DEFAULTS FOR THE FRONTEND TEMPLATE.         *
 * IF YOU NEED PROJECT SPECIFIC SETTINGS                   *
 * THEN ADD THE CHANGES TO THE FILE:                       *
 * eslint.config.js                                        *
 * *********************************************************
 */

/**
 * Base eslint configuration file using the "flat config" format.
 * This configuration includes various ESLint plugins and settings
 * to enforce coding standards and best practices.
 *
 * Things to note:
 *
 * The order of rules matters.
 * If a rule is defined multiple times, the last one will take precedence.
 * Some recommended configs include rules that overrides rules in other recommended configs, which mean these configs should be applied after the other recommended configs.
 *
 * The easiest way to debug the config file is to use the "Eslint config inspector".
 * It is an official tool which shows how the config file is interpreted by ESLint.
 * To use the tool either run "npx @eslint/config-inspector@latest" or "npm run eslint:inspect"
 * See https://github.com/eslint/config-inspector.
 */
import reactPlugin from "eslint-plugin-react";
import onlyWarn from "eslint-plugin-only-warn";
import unusedImports from "eslint-plugin-unused-imports";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import importRule from "eslint-plugin-import";
import reactHooks from "eslint-plugin-react-hooks";
import unicorn from "eslint-plugin-unicorn";
import jsxAlly from "eslint-plugin-jsx-a11y";
import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import functional from "eslint-plugin-functional";
import stylistic from "@stylistic/eslint-plugin";
import prettier from "eslint-config-prettier";
import globals from "globals";
import perfectionist from "eslint-plugin-perfectionist";
import pluginQuery from "@tanstack/eslint-plugin-query";
import sonarjs from "eslint-plugin-sonarjs";
import jsdoc from "eslint-plugin-jsdoc";
import reactRefresh from "eslint-plugin-react-refresh";

/** @type {import('@typescript-eslint/utils').TSESLint.FlatConfig.ConfigFile} */
export default [
  // The reason why these recommended configs are applied here and not below with the others
  // is because ts eslint recommended config rules is not exported as an object but as an array so we can't spread it the same way as other configs.
  // Ts eslints recommended config rules also overrides some of the rules in eslint recommended config, which means we need to apply it after eslint recommended config.
  // See https://typescript-eslint.io/packages/typescript-eslint/#config and select the tab "Without helper"
  eslint.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    name: "Global ignores",
    ignores: [
      "node_modules",
      "dist",
      "public",
      "Backend",
      ".vscode",
      ".husky",
      "src/api",
      "src/api-json-server",
      "webpack.*.js",
      "webpack-dev-server.js",
      "src/**/ServiceWorker.ts",
      "vite-env.d.ts",
      "vite.config.*",
      "vite.utils.*",
      "eslint.config.base.js",
      "eslint.config.js",
      "stylelint.config.base.js",
      "stylelint.config.js",
      "knip.config.base.js",
      "knip.config.js",
      "dev-dist", // Dir created by vite PWA in dev mode
      "vitest.config.*"
    ]
  },
  {
    name: "Base config",
    files: ["**/*.{js,ts,jsx,tsx}"],
    plugins: {
      react: reactPlugin,
      "@typescript-eslint": tseslint.plugin,
      "only-warn": onlyWarn,
      "unused-imports": unusedImports,
      import: importRule,
      "simple-import-sort": simpleImportSort,
      "react-hooks": reactHooks,
      functional,
      unicorn,
      "jsx-a11y": jsxAlly,
      "@stylistic": stylistic,
      perfectionist,
      "@tanstack/query": pluginQuery,
      sonarjs,
      jsdoc,
      "react-refresh": reactRefresh
    },
    languageOptions: {
      parser: tseslint.parser,
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
        ecmaFeatures: {
          jsx: true
        }
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2020,
        ...globals.serviceworker
      }
    },
    linterOptions: {
      reportUnusedDisableDirectives: "error"
    },
    settings: {
      react: {
        version: "detect"
      }
    },
    rules: {
      ...reactPlugin.configs.flat.recommended.rules,
      ...reactPlugin.configs.flat["jsx-runtime"].rules,
      ...reactHooks.configs.recommended.rules,
      ...unicorn.configs.recommended.rules,
      ...jsxAlly.flatConfigs.recommended.rules,
      ...perfectionist.configs["recommended-natural"].rules,
      ...pluginQuery.configs.recommended.rules,
      ...sonarjs.configs.recommended.rules,
      ...jsdoc.configs["flat/recommended-typescript"].rules,
      ...reactRefresh.configs.recommended.rules,
      // Jsdoc plugin rules
      "jsdoc/check-indentation": "warn",
      "jsdoc/check-tag-names": ["warn", { typed: true, definedTags: ["remarks", "typeParam"] }],
      "jsdoc/informative-docs": "warn",
      "jsdoc/require-hyphen-before-param-description": "warn",
      "jsdoc/require-asterisk-prefix": "warn",
      "jsdoc/no-blank-blocks": "warn",
      "jsdoc/no-bad-blocks": "warn",
      // Turned off rules that are part of the plugins recommended config for various reasons
      "jsdoc/require-jsdoc": "off", // We don't want to require jsdoc for all functions
      "jsdoc/require-param-description": "off", // We don't want to require param descriptions for all functions
      "jsdoc/require-returns-description": "off", // We don't want to require return descriptions for all functions
      "jsdoc/require-returns": "off", // Unneccessary to force simply to add @returns in jsdoc if dev deems there is no description to add. Only add when there is actually something to describe
      // Sonarjs plugin rules
      "sonarjs/file-name-differ-from-class": "error",
      // Turned off rules that are part of the plugins recommended config for various reasons
      "sonarjs/function-return-type": "off", // Not useful for us and causes too many warnings
      "sonarjs/prefer-read-only-props": "off", // Not useful for us and causes too many warnings
      "sonarjs/different-types-comparison": "off", // Gives false positives and typescript already checks this
      "sonarjs/no-unused-vars": "off", // Already checked by typescript eslint
      "sonarjs/array-callback-without-return": "off", // Already checked by js eslint
      "sonarjs/pseudo-random": "off", // Not sure if it is useful for us. COME BACK TO THIS ONE
      "sonarjs/todo-tag": "off", // We don't want warnings for TODO comments
      "sonarjs/deprecation": "off", // Large performance impact on eslint. Causes large slowdowns in vscode with the eslint extension. If we need this rule, we can enable it in CI
      "sonarjs/no-commented-code": "off", // Code should obviously not be commented out in production. However this rule has a large performance impact on eslint. See reasoning for "sonarjs/deprecation" rule.
      // Perfectionist plugin rules
      "perfectionist/sort-jsx-props": [
        "warn",
        {
          ignoreCase: false,
          groups: ["reserved", "shorthand-prop", "prop", "callback"],
          customGroups: [
            {
              groupName: "reserved",
              elementNamePattern: "^(key|ref)$"
            },
            {
              groupName: "callback",
              elementNamePattern: "^on[A-Z]"
            }
          ]
        }
      ],
      // Turned off rules that are part of the plugins recommended config for various reasons
      "perfectionist/sort-imports": "off", // Turned off in favor of using "eslint-plugin-simple-import-sort"
      "perfectionist/sort-objects": [
        "error",
        {
          type: "unsorted", // Don't sort objects passed to react-query useInfiniteQuery since they need to be in a specific order. See https://tanstack.com/query/latest/docs/eslint/infinite-query-property-order
          useConfigurationIf: {
            callingFunctionNamePattern: "^useInfiniteQuery$"
          }
        },
        {
          type: "natural" // Fallback configuration
        }
      ],
      // Stylistic plugin rules
      "@stylistic/dot-location": ["warn", "property"],
      "@stylistic/newline-per-chained-call": ["error", { ignoreChainWithDepth: 4 }],
      "@stylistic/no-confusing-arrow": "warn",
      "@stylistic/no-multiple-empty-lines": ["error", { max: 2, maxEOF: 0 }],
      "@stylistic/spaced-comment": "warn",
      "@stylistic/lines-around-comment": ["warn", { beforeBlockComment: true, allowBlockStart: true, allowInterfaceStart: true }],
      "@stylistic/padding-line-between-statements": [
        "warn",
        { blankLine: "always", prev: "*", next: ["interface", "type", "return", "function", "export"] }
      ],
      "@stylistic/jsx-curly-brace-presence": ["warn", "never"],
      "@stylistic/jsx-newline": ["warn", { prevent: true }],
      "@stylistic/jsx-pascal-case": "warn",
      // Unicorn plugin rules
      "unicorn/prefer-ternary": ["warn", "only-single-line"],
      "unicorn/filename-case": ["warn", { case: "pascalCase" }],
      // Turned off rules that are part of the plugins recommended config for various reasons
      "unicorn/prevent-abbreviations": "off", // Causes too many warnings and requires lots of configuration to be useful for us
      "unicorn/no-useless-undefined": "off", // Not necessary for our projects
      "unicorn/switch-case-braces": "off", // A style preference that is not desirable for our projects
      "unicorn/no-null": "off", // This is an opinionated rule that is not suitable for our projects as we use null in responses from backend
      "unicorn/prefer-number-properties": "off",
      "unicorn/no-array-reduce": "off", // This is an opionated rule that warns against all usage of reduce except for summing numbers. However, we frequently use reduce for other purposes such as creating an object from an array.
      "unicorn/numeric-separators-style": "off",
      "unicorn/consistent-function-scoping": "off",
      "unicorn/consistent-destructuring": "off",
      "unicorn/number-literal-case": "off",
      "unicorn/prefer-global-this": "off", // Unsure about the effects. COME BACK TO THIS ONE.
      // Functional plugin rules
      "functional/immutable-data": [
        "error",
        {
          ignoreClasses: "fieldsOnly", // Ignore mutations in class methods (ie this.classField = 1), but not in functions
          // displayName is commonly mutated property on React components for debugging purposes
          // current is commonly mutated property on React refs
          // telemetryItem["properties"] is mutated to add custom properties to telemetry in app insights
          // href and download are commonly mutated properties on anchor elements
          ignoreIdentifierPattern: [".displayName", ".current", 'telemetryItem\\.\\["properties"\\]', ".href", ".download"]
        }
      ],
      "functional/no-this-expressions": "warn",
      // Javascript rules
      "prefer-object-spread": "error",
      "operator-assignment": "error",
      "object-shorthand": "error",
      "no-useless-return": "error",
      "no-useless-rename": "error",
      "no-useless-concat": "warn",
      "no-useless-computed-key": "warn",
      "no-unneeded-ternary": "warn",
      "no-return-assign": "warn",
      "no-nested-ternary": "warn",
      "no-multi-assign": "warn",
      "no-lonely-if": "warn",
      "no-lone-blocks": "warn",
      "no-implicit-coercion": "warn",
      "max-nested-callbacks": ["error", 5],
      "max-depth": ["error", 4],
      "default-case-last": "warn",
      eqeqeq: ["warn", "always"],
      "no-throw-literal": "warn", // Why did I turn this off before?
      "prefer-destructuring": "warn",
      "prefer-template": "warn",
      "no-console": "warn",
      "no-await-in-loop": "warn",
      "no-template-curly-in-string": "error",
      curly: "warn",
      "no-else-return": ["warn", { allowElseIf: true }],
      "prefer-arrow-callback": "warn",
      "func-style": "warn",
      "no-param-reassign": "warn",
      "one-var": ["warn", "never"],
      "no-alert": "warn",
      "array-callback-return": "warn",
      // Typescript plugin rules
      // Part of recommended but with different options
      "@typescript-eslint/prefer-nullish-coalescing": [
        "warn",
        {
          ignoreMixedLogicalExpressions: true,
          ignorePrimitives: true
        }
      ],
      "@typescript-eslint/no-unnecessary-condition": "warn",
      "@typescript-eslint/switch-exhaustiveness-check": "warn",
      "@typescript-eslint/prefer-reduce-type-parameter": "warn",
      "@typescript-eslint/no-useless-empty-export": "warn",
      "@typescript-eslint/method-signature-style": "warn",
      "@typescript-eslint/consistent-type-imports": "warn",
      "@typescript-eslint/consistent-type-exports": "warn",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": "warn",
      "@typescript-eslint/no-misused-promises": ["warn", { checksVoidReturn: false }], // Part of recommended but with different options
      "@typescript-eslint/naming-convention": [
        "error",
        {
          selector: "variable",
          format: ["camelCase", "UPPER_CASE"],
          leadingUnderscore: "allow",
          filter: {
            // refresh_a_token is from a msal library, a third party library, so we don't want to enforce our naming convention on it.
            regex: "Context|TrackPageView|DevExtraInfo|lazy|Component|Modal|Routes|Icon|Render|Komponent|Wrapper|refresh_a_token",
            match: false
          }
        },
        {
          selector: ["parameter", "parameterProperty"],
          format: ["camelCase"],
          leadingUnderscore: "allow",
          filter: { regex: "DevExtraInfo|Props|Render|Component", match: false }
        },
        {
          selector: ["objectLiteralMethod", "objectLiteralProperty", "typeProperty"],
          format: ["camelCase"]
        },
        {
          selector: ["interface", "enum", "typeAlias"],
          format: ["PascalCase"],
          custom: {
            regex: "^I[A-Z]",
            match: false
          }
        },
        {
          selector: [
            "classProperty",
            "objectLiteralProperty",
            "typeProperty",
            "classMethod",
            "objectLiteralMethod",
            "typeMethod",
            "accessor",
            "enumMember"
          ],
          format: null,
          modifiers: ["requiresQuotes"]
        },
        {
          selector: ["objectLiteralMethod", "objectLiteralProperty", "typeProperty"],
          format: null,
          filter: {
            // Object literal property names "invalid_type_error" and "required_errorused" are used by the library "zod"
            regex: "Modal|Component|Render|__html|Header|Cell|Filter|Mui|Authorization|Props|Komponent|invalid_type_error|required_error",
            match: true
          }
        }
      ],
      // Disabling following eslint rules, so to use equivalent typescript rules
      // (you must disable the base rule as it can report incorrect errors)
      "default-param-last": "off",
      "no-return-await": "off",
      "no-useless-constructor": "off",
      "no-unused-vars": "off",
      "max-params": "off",
      "no-use-before-define": "off",
      "no-loop-func": "off",
      "@typescript-eslint/default-param-last": "warn",
      "@typescript-eslint/return-await": "warn",
      "@typescript-eslint/no-useless-constructor": "warn",
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "@typescript-eslint/max-params": ["error", { max: 5 }],
      "@typescript-eslint/no-use-before-define": "error",
      "@typescript-eslint/no-loop-func": "error",
      // Turned off rules that are part of the plugins recommended config for various reasons
      "@typescript-eslint/non-nullable-type-assertion-style": "off",
      "@typescript-eslint/no-floating-promises": "off", // We want to allow floating promises. Common usage in useEffect or squawk actions
      // React plugin rules
      "react/function-component-definition": ["warn", { namedComponents: "function-declaration" }],
      "react/no-multi-comp": ["warn", { ignoreStateless: true }],
      "react/jsx-fragments": ["warn", "syntax"], // (Fixable) Enforce shorthand syntax for React fragments "<></>"
      "react/no-this-in-sfc": "error", // Disallow usage of "this" in functional component.
      "react/self-closing-comp": ["warn", { component: true, html: true }], // (Fixable) React and html components without children must be self-closed to avoid unnecessary extra closing tag.
      "react/jsx-boolean-value": ["warn", "never"], // (Fixable) Enforce boolean attributes notation: "open" instead of "open={true}"
      "react/jsx-no-useless-fragment": ["warn", { allowExpressions: true }], // (Fixable) Disallow unnecessary fragments
      "react/jsx-key": "warn", // Enforce key-prop on jsx arrays
      "react/void-dom-elements-no-children": "warn",
      "react/no-unescaped-entities": "warn", // Disallow/forbid certain unnecessary characters that can lead to errors on comps
      "react/no-unknown-property": "warn", // Enforce camelCased naming convetion for DOM props
      "react/jsx-no-comment-textnodes": "warn",
      "react/jsx-no-bind": ["warn", { allowArrowFunctions: true }],
      "react/button-has-type": ["error", { button: true, submit: false, reset: false }], // Only allow type="button" on button
      "react/jsx-handler-names": "warn",
      "react/no-unused-prop-types": "warn",
      "react/jsx-max-depth": ["warn", { max: 10 }],
      "react/no-unstable-nested-components": ["warn", { allowAsProps: true }],
      "react/hook-use-state": ["warn", { allowDestructuredState: true }],
      "react/no-object-type-as-default-prop": "warn", // To prevent potential unnecessary rerenders, and performance regressions.
      "react/no-array-index-key": "warn",
      // Unused imports plugin rules. This plugin is only used in npm scripts to remove unused imports
      "unused-imports/no-unused-imports": "off", // Turned off since we only use it through npm script.
      "unused-imports/no-unused-vars": "off", // Turned off since we use typescript linting rule instead
      // Import plugin rules
      "import/first": "warn", // (Fixable)
      "import/newline-after-import": "warn", // (Fixable)
      "import/no-anonymous-default-export": "warn",
      "import/no-namespace": "warn",
      "import/no-unused-modules": "warn",
      "import/consistent-type-specifier-style": ["warn", "prefer-top-level"],
      "import/no-duplicates": "error",
      // Simple import sort plugin rules
      "sort-imports": "off", // Turned off in favor of using "eslint-plugin-simple-import-sort"
      "import/order": "off", // Turned off in favor of using "eslint-plugin-simple-import-sort"
      "simple-import-sort/imports": [
        "warn",
        {
          groups: [
            // Node.js builtins. You could also generate this regex if you use a `.js` config.
            // For example: `^(${require("module").builtinModules.join("|")})(/|$)`
            [
              "^(assert|buffer|child_process|cluster|console|constants|crypto|dgram|dns|domain|events|fs|http|https|module|net|os|path|punycode|querystring|readline|repl|stream|string_decoder|sys|timers|tls|tty|url|util|vm|zlib|freelist|v8|process|async_hooks|http2|perf_hooks)(/.*|$)"
            ],
            // Packages. `react` related packages come first.
            ["^react", "^@?\\w"],
            ["^.*\\u0000$"],
            // Internal packages.
            ["^(@|@company|@ui|components|utils|config|api|css|images|vendored-lib)(/.*|$)"],
            ["^(Src/api)(/.*|$)"],
            ["^(Src/components)(/.*|$)"],
            ["^(Src/hooks)(/.*|$)"],
            ["^(Src)(/.*|$)"],
            // Side effect imports.
            ["^\\u0000"],
            // Parent imports. Put `..` last.
            ["^\\.\\.(?!/?$)", "^\\.\\./?$"],
            // Other relative imports. Put same-folder imports and `.` last.
            ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"],
            // Style imports.
            ["^.+\\.s?css$"]
          ]
        }
      ]
    }
  },
  {
    // Turn off max lines for component files
    // because this rules also counts imports which can take up alot of lines in components.
    // We use the rule "max-lines-per-function" for components instead.
    name: "Disable max lines for component files",
    files: ["src/**/*.tsx"],
    rules: {
      "max-lines": ["off", 250]
    }
  },
  {
    // Routes.tsx usually contains a named export of the routes array.
    // Root.tsx sometimes contains named exports (such as app insights).
    name: "Default exports in components and hooks",
    files: ["src/**/*.tsx", "src/**/use*.*", "src/hooks/*"],
    ignores: ["src/**/*Context.tsx", "src/Root.tsx", "src/**/Routes.tsx"],
    rules: {
      "import/prefer-default-export": "error"
    }
  },
  {
    name: "Max lines per function for non components",
    files: ["src/**/*.ts"],
    ignores: ["src/hooks/**/*"],
    rules: {
      "max-lines-per-function": ["warn", 40]
    }
  },
  {
    name: "Max lines per function for components",
    files: ["src/**/*.tsx"],
    ignores: ["src/hooks/**/*", "src/**/Routes.tsx"],
    rules: {
      "max-lines-per-function": ["warn", 250]
    }
  },
  {
    // Hooks, HoC (Higher-Order Component) should adhere to camel case naming
    // See https://react.dev/learn/reusing-logic-with-custom-hooks#hook-names-always-start-with-use
    name: "Hooks naming convention",
    files: ["src/**/use*.*", "src/**/Use*.*", "src/hooks/*", "src/**/with*.tsx"],
    // Don't apply rule to files starting with "User" such as "UserContext", "UserProvider" which are common in our projects.
    ignores: ["src/**/User*"],
    rules: {
      "unicorn/filename-case": ["error", { case: "camelCase" }]
    }
  },
  {
    name: "Template d.ts file rules",
    files: ["src/interfaces/TemplateGlobals.d.ts", "src/interfaces/custom.d.ts", "src/interfaces/ReactRouterExtended.d.ts"],
    rules: {
      "@stylistic/spaced-comment": "off",
      "@typescript-eslint/naming-convention": "off",
      "sonarjs/use-type-alias": "off"
    }
  },
  {
    name: "General d.ts file rules",
    files: ["src/**/*.d.ts"],
    rules: {
      "sonarjs/unused-import": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "unused-imports/no-unused-imports": "off"
    }
  },
  {
    name: "Disable unicorn rule for disable directive in api folder",
    files: ["src/api/*"],
    rules: {
      "unicorn/no-abusive-eslint-disable": "off"
    }
  },
  {
    name: "Rules for Routes.tsx",
    files: ["src/**/Routes.tsx"],
    rules: {
      "@typescript-eslint/naming-convention": "off", // Routes.tsx can sometimes contain lazy loaded components defined as variables with PascalCase naming, which will conflict with this rule.
      "perfectionist/sort-objects": "off" // We don't want to sort objects in this file because we want the routes array to be in the order they are defined for readability.
    }
  },
  {
    name: "Special rules for store and squawk files",
    files: ["src/**/store/*", "src/**/squawk/*", "src/**/Store/*", "src/**/Squawk/*"],
    rules: {
      "@typescript-eslint/unbound-method": "off"
    }
  },
  {
    // vite-env.d.ts is part of the official vite template and should not be linted.
    name: "vite-env.d.ts rules",
    files: ["src/vite-env.d.ts"],
    rules: {
      "@typescript-eslint/naming-convention": "off"
    }
  },
  {
    // *Context.tsx files are reported by this rule but they don't usually export components.
    // Root.tsx/App.tsx sometimes contains named exports (such as app insights) and is acceptable not to follow this rule since we don't update this file often.
    // Routes.tsx sometimes contains lazy loaded components which this rule doesn't handle well.
    name: "Disable react-refresh rules for specific files",
    files: ["src/**/*Context.tsx", "src/Root.tsx", "src/**/Routes.tsx", "src/App.tsx"],
    rules: {
      "react-refresh/only-export-components": "off"
    }
  },
  {
    // vite-env.d.ts and main.tsx are part of the official vite template
    // and are allowed to have their original filename for keeping consistency with the template.
    name: "Filename exceptions",
    files: ["src/vite-env.d.ts", "src/main.tsx"],
    rules: {
      "unicorn/filename-case": "off"
    }
  },
  {
    // Prettier config rules should come last so it can override conflicting rules.
    // It disables rules from other plugins that conflict with prettier.
    // See https://github.com/prettier/eslint-config-prettier?tab=readme-ov-file#installation.
    name: "Prettier config rules",
    rules: prettier.rules
  },
  {
    name: "Override preffier config rules",
    rules: {
      "@stylistic/newline-per-chained-call": ["error", { ignoreChainWithDepth: 4 }],
      "@stylistic/jsx-newline": ["warn", { prevent: true }],
      "@stylistic/lines-around-comment": ["warn", { beforeBlockComment: true, allowBlockStart: true, allowInterfaceStart: true }],
      "@stylistic/dot-location": ["warn", "property"],
      "@stylistic/no-multiple-empty-lines": ["error", { max: 2, maxEOF: 0 }]
    }
  }
];
