/**
 * *********************************************************
 * DO NOT EDIT THIS FILE IN YOUR PROJECT UNLESS NECESSARY. *
 * IT CONTAINS DEFAULTS FOR THE FRONTEND TEMPLATE.         *
 * IF YOU NEED PROJECT SPECIFIC SETTINGS                   *
 * THEN ADD THE CHANGES TO THE FILE:                       *
 * knip.config.js                                          *
 * *********************************************************
 */

/** @type {import("knip").KnipConfig} */
export default {
  entry: ["eslint.config.base.js", "vite.config.base.ts"],
  project: ["src/**/*.{ts,tsx}"],
  ignore: ["src/api/**/*", "src/**/*.d.ts"],
  ignoreBinaries: ["pwsh", "dotnet"],
  ignoreDependencies: ["check-dependencies", "@typescript-eslint/utils", "react-compiler-runtime"],
  paths: {
    "Src/*": ["./src/*"]
  }
};
