/**
 * *********************************************************
 * DO NOT EDIT THIS FILE IN YOUR PROJECT UNLESS NECESSARY. *
 * IT CONTAINS DEFAULTS FOR THE FRONTEND TEMPLATE.         *
 * IF YOU NEED PROJECT SPECIFIC SETTINGS                   *
 * THEN ADD THE CHANGES TO THE FILE:                       *
 * stylelint.config.js                                     *
 * *********************************************************
 */

/** @type {import('stylelint').Config} */
export default {
  defaultSeverity: "warning",
  cache: true,
  reportNeedlessDisables: true,
  reportUnscopedDisables: true,
  reportDescriptionlessDisables: true,
  reportInvalidScopeDisables: true,
  extends: "stylelint-config-standard",
  rules: {
    "selector-max-id": 0, // Warn on ID selectors (e.g., #id)
    "selector-max-class": 1, // Warn if more than 1 class selector is used in a single rule (e.g., .class1.class2)
    "selector-max-type": 0, // Warn on type selectors (e.g., html, body, div, span)
    "selector-max-combinators": 0, // Warn on combinators (e.g., >, +, ~)
    "selector-max-compound-selectors": 1, // Warn if more than 1 compound selector is used in a single rule (e.g., div.class1.class2)
    "selector-no-qualifying-type": true, // Warn if a type selector is used in combination with a class or ID selector (e.g., div.class, span#id)
    "selector-class-pattern": ["^.[a-z]([a-z0-9-]+)?(__([a-z0-9]+-?)+)?(--([a-z0-9]+-?)+){0,2}$", { message: "Selector does not match BEM pattern" }] // Enforce BEM naming convention for class selectors
  },
  overrides: [
    {
      files: ["src/styles/Site.css"],
      rules: {
        "no-empty-source": null
      }
    }
  ],
  ignoreFiles: ["node_modules", "dist", "public", "Backend", "semantic-theme", "index.html", "index.ejs"]
};
