/**
 * *********************************************************
 * DO NOT EDIT THIS FILE IN YOUR PROJECT UNLESS NECESSARY. *
 * IT CONTAINS DEFAULTS FOR THE FRONTEND TEMPLATE.         *
 * IF YOU NEED PROJECT SPECIFIC SETTINGS                   *
 * THEN ADD THE CHANGES TO THE FILE:                       *
 * vite.config.ts                                          *
 * *********************************************************
 */

import { defineConfig, loadEnv } from "vite";
import checker from "vite-plugin-checker";
import { visualizer } from "rollup-plugin-visualizer";
import { VitePWA } from "vite-plugin-pwa";
import manifestJson from "./manifest.json";

import react, { reactCompilerPreset } from "@vitejs/plugin-react";
import babel from "@rolldown/plugin-babel";

/**
 * Custom vite plugin.
 * Injects a <base> tag into the generated HTML.
 */
const injectBaseTagPlugin = (baseUrl: string) => {
  return {
    name: "inject-base-tag",
    enforce: "post",
    transformIndexHtml(html: string) {
      if (baseUrl && baseUrl !== "/") {
        // Remove any existing <base> tag
        html = html.replace(/<base[^>]*>/gi, "");
        // Inject <base> tag after <head>
        return html.replace(/<head(\s*[^>]*)>/i, `<head$1>\n    <base href="${baseUrl}">`);
      }
      return html;
    }
  };
};

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  const envConfig = loadEnv(mode, process.cwd(), "CONFIG");
  const envVite = loadEnv(mode, process.cwd(), "VITE");
  const env = { ...envConfig, ...envVite };
  const proxyTarget = env.CONFIG_PROXY_URL?.trim();
  const vscodeDebug = process.argv[process.argv.length - 1] === "vscodedebug";

  console.table(env);

  const baseUrl = env.VITE_BASE_URL ?? "/";

  return {
    base: baseUrl, // Needed for correct asset loading and routing when the app is not served from the root
    build: {
      sourcemap: mode === "production" ? "hidden" : false
    },
    server: {
      proxy: proxyTarget
        ? {
            "/api": proxyTarget
          }
        : undefined,
      port: env.CONFIG_PORT !== "" ? parseInt(env.CONFIG_PORT) : undefined,
      // VS Code debug in launch.json will open the browser automatically
      open: vscodeDebug ? false : env.CONFIG_OPEN === "true" ? true : env.CONFIG_OPEN
    },
    preview: {
      open: env.CONFIG_OPEN === "true" ? true : env.CONFIG_OPEN
    },
    resolve: {
      tsconfigPaths: true // Enable path aliasing configured in tsconfig.json
    },
    plugins: [
      react(),
      // https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#react-compiler
      env.CONFIG_REACT_COMPILER === "true" &&
        babel({
          presets: [
            reactCompilerPreset({
              target: "18" // Remove this and dep "react-compiler-runtime" from frontend template when it uses React 19 or higher, as the preset will then target React 19 by default
            })
          ]
        }),
      mode === "development" &&
        checker({
          overlay: {
            initialIsOpen: false
          },
          typescript: {
            tsconfigPath: "./tsconfig.app.json"
          },
          eslint:
            env.CONFIG_ESLINT === "false"
              ? false
              : {
                  lintCommand: 'eslint "./src/**/*.{ts,tsx}"',
                  useFlatConfig: true
                }
        }),
      env.CONFIG_PWA === "true" &&
        VitePWA({
          registerType: "autoUpdate",
          includeAssets: ["favicon.ico", "favicon.svg", "apple-touch-icon-180x180.png", "mask-icon.svg"],
          pwaAssets: {},
          manifest: {
            ...(manifestJson as object) // Type casting to avoid ts errors
          }
        }),
      env.CONFIG_BUNDLE_ANALYZE === "true" && mode === "production" && visualizer(),
      injectBaseTagPlugin(baseUrl)
    ].filter(Boolean)
  };
});
