// <auto-generated />
using System;
using HomeHelper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeHelper.Migrations
{
    [DbContext(typeof(HomehelperContext))]
    [Migration("20260902090705_MakeTemplatesChildOwned")]
    partial class MakeTemplatesChildOwned
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HomeHelper.Data.Child", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildId"));

                    b.Property<int?>("ActiveItemTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChildId");

                    b.HasIndex("ActiveItemTemplateId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("HomeHelper.Data.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int>("HomeQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ItemTemplateEntryId")
                        .HasColumnType("int");

                    b.Property<int>("KindergartenQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ItemId");

                    b.HasIndex("ChildId");

                    b.HasIndex("ItemTemplateEntryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("HomeHelper.Data.ItemTemplate", b =>
                {
                    b.Property<int>("ItemTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemTemplateId"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ItemTemplateId");

                    b.HasIndex("ChildId");

                    b.ToTable("ItemTemplates");
                });

            modelBuilder.Entity("HomeHelper.Data.ItemTemplateEntry", b =>
                {
                    b.Property<int>("ItemTemplateEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemTemplateEntryId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ItemTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ItemTemplateEntryId");

                    b.HasIndex("ItemTemplateId");

                    b.ToTable("ItemTemplateEntries");
                });

            modelBuilder.Entity("HomeHelper.Data.ParentChildLink", b =>
                {
                    b.Property<int>("ParentChildLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentChildLinkId"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ParentChildLinkId");

                    b.HasIndex("ChildId");

                    b.HasIndex("UserId", "ChildId")
                        .IsUnique();

                    b.ToTable("ParentChildLinks");
                });

            modelBuilder.Entity("HomeHelper.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("UserId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeHelper.Data.Child", b =>
                {
                    b.HasOne("HomeHelper.Data.ItemTemplate", "ActiveItemTemplate")
                        .WithMany()
                        .HasForeignKey("ActiveItemTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveItemTemplate");
                });

            modelBuilder.Entity("HomeHelper.Data.Item", b =>
                {
                    b.HasOne("HomeHelper.Data.Child", "Child")
                        .WithMany("Items")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeHelper.Data.ItemTemplateEntry", "ItemTemplateEntry")
                        .WithMany("Items")
                        .HasForeignKey("ItemTemplateEntryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Child");

                    b.Navigation("ItemTemplateEntry");
                });

            modelBuilder.Entity("HomeHelper.Data.ItemTemplate", b =>
                {
                    b.HasOne("HomeHelper.Data.Child", "Child")
                        .WithMany("ItemTemplates")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("HomeHelper.Data.ItemTemplateEntry", b =>
                {
                    b.HasOne("HomeHelper.Data.ItemTemplate", "ItemTemplate")
                        .WithMany("Entries")
                        .HasForeignKey("ItemTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemTemplate");
                });

            modelBuilder.Entity("HomeHelper.Data.ParentChildLink", b =>
                {
                    b.HasOne("HomeHelper.Data.Child", "Child")
                        .WithMany("ParentLinks")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeHelper.Data.User", "User")
                        .WithMany("ChildLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeHelper.Data.Child", b =>
                {
                    b.Navigation("ItemTemplates");

                    b.Navigation("Items");

                    b.Navigation("ParentLinks");
                });

            modelBuilder.Entity("HomeHelper.Data.ItemTemplate", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("HomeHelper.Data.ItemTemplateEntry", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("HomeHelper.Data.User", b =>
                {
                    b.Navigation("ChildLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
