trigger: none

pool: "Linux"

steps:
  - task: UseNode@1
    displayName: Download Node.js
    inputs:
      version: "22.22.x"
  - task: Npm@1
    displayName: "npm ci"
    inputs:
      command: ci
      workingDir: Frontend
      verbose: false
  - task: PowerShell@2
    displayName: Verify linting and prettier
    inputs:
      targetType: "inline"
      script: "npm run lint:check:ci && npm run format:check"
      failOnStderr: true
      showWarnings: false
      workingDirectory: "Frontend"
      ignoreLASTEXITCODE: true
