/**
 * ***************************************************
 * DO NOT EDIT THIS FILE.                            *
 * IT CONTAINS DEFAULTS FOR THE FRONTEND TEMPLATE.   *
 * IF YOU WANT TO ADD THINGS HIGH UP IN              *
 * THE COMPONENT TREE THEN DO SO IN App.tsx          *
 * ***************************************************
 */

import React, { StrictMode } from "react";
import ReactDOM, { createRoot } from "react-dom/client";

import App from "./App";

if (import.meta.env.MODE === "development" && import.meta.env.VITE_REACT_SCAN === "true" && typeof globalThis !== "undefined") {
  // Exception to the linting rule to get around issues with top level await for this specific package import.
  // eslint-disable-next-line unicorn/prefer-top-level-await
  import("react-scan").then((reactScan) => {
    reactScan.scan({
      enabled: true
    });
  });
}

createRoot(document.querySelector("#root")!).render(
  <StrictMode>
    <App />
  </StrictMode>
);

if (import.meta.env.MODE === "development" && import.meta.env.VITE_REACT_AXE === "true") {
  // Exception to the linting rule to get around issues with top level await for this specific package import.
  // eslint-disable-next-line unicorn/prefer-top-level-await
  import("@axe-core/react").then((axe) => {
    axe.default(React, ReactDOM, 1000);
  });
}

if (import.meta.env.MODE === "development" && import.meta.env.VITE_LOCATOR_JS === "true") {
  // Exception to the linting rule to get around issues with top level await for this specific package import.
  // eslint-disable-next-line unicorn/prefer-top-level-await
  import("@locator/runtime").then((locatorJs) => {
    locatorJs.default();
  });
}
