/// <reference types="vite/client" />

/**
 * ***************************************************
 * DO NOT EDIT THIS FILE IN YOUR PROJECT.            *
 * IT CONTAINS DEFAULTS FOR THE FRONTEND TEMPLATE.   *
 * IF YOU NEED TO DO SIMILIAR PROJECT SPECIFIC       *
 * THINGS, DO SO IN A d.ts FILE IN src/interfaces,   *
 * USUALLY A FILE NAMED Globals.d.ts                 *
 * ***************************************************
 */

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

interface ImportMetaEnv {
  readonly VITE_APP_LANG?: string;
  readonly VITE_APP_TITLE?: string;
  readonly VITE_BASE_URL?: string;
  readonly VITE_LOCATOR_JS?: string;
  readonly VITE_REACT_AXE?: string;
  readonly VITE_REACT_SCAN?: string;
}
